// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7KwY7UrPPkd8xaQIXOxVH2CnQDV43QHs',
    appId: '1:551132849797:web:3278ee634976fcc8e96bec',
    messagingSenderId: '551132849797',
    projectId: 'ecomrce-app-5b2a4',
    authDomain: 'ecomrce-app-5b2a4.firebaseapp.com',
    storageBucket: 'ecomrce-app-5b2a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4EcfKKJ7Ow_Bm38MAk_Inm7oznbCOyxI',
    appId: '1:551132849797:android:61e94fbdaa004bb4e96bec',
    messagingSenderId: '551132849797',
    projectId: 'ecomrce-app-5b2a4',
    storageBucket: 'ecomrce-app-5b2a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBAH-HcApiBVK0UUyC3NRFQGRk9tKeKk',
    appId: '1:551132849797:ios:cd7613c3657463ace96bec',
    messagingSenderId: '551132849797',
    projectId: 'ecomrce-app-5b2a4',
    storageBucket: 'ecomrce-app-5b2a4.appspot.com',
    androidClientId: '551132849797-l86pie6peqif6lavgn57e7t8tikd7ksd.apps.googleusercontent.com',
    iosClientId: '551132849797-haf0ksfftetj5789tgu3n4b3ot51paqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomarce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxBAH-HcApiBVK0UUyC3NRFQGRk9tKeKk',
    appId: '1:551132849797:ios:cd7613c3657463ace96bec',
    messagingSenderId: '551132849797',
    projectId: 'ecomrce-app-5b2a4',
    storageBucket: 'ecomrce-app-5b2a4.appspot.com',
    androidClientId: '551132849797-l86pie6peqif6lavgn57e7t8tikd7ksd.apps.googleusercontent.com',
    iosClientId: '551132849797-haf0ksfftetj5789tgu3n4b3ot51paqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomarce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7KwY7UrPPkd8xaQIXOxVH2CnQDV43QHs',
    appId: '1:551132849797:web:0781b15019d19935e96bec',
    messagingSenderId: '551132849797',
    projectId: 'ecomrce-app-5b2a4',
    authDomain: 'ecomrce-app-5b2a4.firebaseapp.com',
    storageBucket: 'ecomrce-app-5b2a4.appspot.com',
  );
}
